dist: xenial
language: python
python: 3.7

install:
  - pip install coverage
  - pip install pytest-cov
  - pip install codacy-coverage

script:
  - pytest --cov='stdPhylogeny2vine'
  - coverage xml
  - python-codacy-coverage -r coverage.xml